import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import React from 'react'
import Image from 'next/image'
import Search from "~/components/landing/Search";
import Popular from "~/components/landing/Popular"
import Specials from "~/components/landing/Specials"
import Newsletter from "~/components/landing/Newsletter"
import {BsChatRightDots} from "react-icons/bs"
import {AiOutlineCheck} from 'react-icons/ai'
import Calendar from "~/components/modals/Calendar";
import Holiday_types from "~/components/modals/Holiday_types"
import Destination from "~/components/modals/Destination"


import { api } from "../utils/api";


const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Travel app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-figtree">
    <div className="z-50 fixed bottom-2 sm:bottom-4 right-2 sm:right-4"><button className="bg-indigo-900 border border-gray-50 p-2 text-xs sm:text-lg flex flex-row items-center justify-center gap-1 shadow-lg text-white rounded-lg hover:opacity-50"><BsChatRightDots/>Let's Chat</button></div>
    <div className=" bg-mauritiusBanner z-0 flex flex-col items-center justify-center bg-cover bg-center h-full w-full sm:h-1/2">
      <Search category="Destination" category2="Travel category"/>

    </div>

    <div className="relative w-full flex items-center justify-center">
      <div className="relative h-full w-4/5 2xl:w-3/4 rounded-lg flex flex-row px-4 pb-4 ">
        <div className="sm:flex sm:flex-row w-full bg-white rounded-lg border border-gray-200">
          <div className="w-full h-48 sm:h-full flex justify-center sm:flex-1 "><Image src="/images/amalfi.jpeg" alt="almafi coast" height={48} width={500} className="rounded-t-lg sm:rounded-none sm:rounded-l-lg"></Image></div>
            <div className="p-5 flex sm:w-3/4 flex-col">
              <h1 className="mb-3 sm:text-xl font-bold">Let us assist you!</h1>
              <ul className="flex flex-col gap-2 text-sm">
                <li className="flex flex-row gap-2"><span><AiOutlineCheck color="green"/></span><p>Service</p></li>
                <li className="flex flex-row gap-2"><span><AiOutlineCheck color="green"/></span><p>Peace of Mind</p></li>
                <li className="flex flex-row gap-2"><span><AiOutlineCheck color="green"/></span><p>Value for Money</p></li>
                <li className="flex flex-row gap-2"><span><AiOutlineCheck color="green"/></span><p>Travel made Easy</p></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <Newsletter/>
   </div>
      
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
